import type { User, Location, Vehicle, Database } from "./types";

export const users: Database<User> = {
  query: "SELECT * FROM users",
  data: [
    { id: 0, name: "User 0", age: 24, address: "Address 0" },
    { id: 1, name: "User 1", age: 37, address: "Address 1" },
    { id: 2, name: "User 2", age: 71, address: "Address 2" },
    { id: 3, name: "User 3", age: 85, address: "Address 3" },
    { id: 4, name: "User 4", age: 95, address: "Address 4" },
    { id: 5, name: "User 5", age: 22, address: "Address 5" },
    { id: 6, name: "User 6", age: 52, address: "Address 6" },
    { id: 7, name: "User 7", age: 5, address: "Address 7" },
    { id: 8, name: "User 8", age: 76, address: "Address 8" },
    { id: 9, name: "User 9", age: 79, address: "Address 9" },
    { id: 10, name: "User 10", age: 67, address: "Address 10" },
    { id: 11, name: "User 11", age: 51, address: "Address 11" },
    { id: 12, name: "User 12", age: 59, address: "Address 12" },
    { id: 13, name: "User 13", age: 83, address: "Address 13" },
    { id: 14, name: "User 14", age: 73, address: "Address 14" },
    { id: 15, name: "User 15", age: 42, address: "Address 15" },
    { id: 16, name: "User 16", age: 88, address: "Address 16" },
    { id: 17, name: "User 17", age: 17, address: "Address 17" },
    { id: 18, name: "User 18", age: 67, address: "Address 18" },
    { id: 19, name: "User 19", age: 82, address: "Address 19" },
    { id: 20, name: "User 20", age: 78, address: "Address 20" },
    { id: 21, name: "User 21", age: 29, address: "Address 21" },
    { id: 22, name: "User 22", age: 62, address: "Address 22" },
    { id: 23, name: "User 23", age: 83, address: "Address 23" },
    { id: 24, name: "User 24", age: 41, address: "Address 24" },
    { id: 25, name: "User 25", age: 56, address: "Address 25" },
    { id: 26, name: "User 26", age: 56, address: "Address 26" },
    { id: 27, name: "User 27", age: 90, address: "Address 27" },
    { id: 28, name: "User 28", age: 41, address: "Address 28" },
    { id: 29, name: "User 29", age: 69, address: "Address 29" },
    { id: 30, name: "User 30", age: 21, address: "Address 30" },
    { id: 31, name: "User 31", age: 44, address: "Address 31" },
    { id: 32, name: "User 32", age: 45, address: "Address 32" },
    { id: 33, name: "User 33", age: 63, address: "Address 33" },
    { id: 34, name: "User 34", age: 45, address: "Address 34" },
    { id: 35, name: "User 35", age: 82, address: "Address 35" },
    { id: 36, name: "User 36", age: 88, address: "Address 36" },
    { id: 37, name: "User 37", age: 52, address: "Address 37" },
    { id: 38, name: "User 38", age: 79, address: "Address 38" },
    { id: 39, name: "User 39", age: 55, address: "Address 39" },
    { id: 40, name: "User 40", age: 86, address: "Address 40" },
    { id: 41, name: "User 41", age: 24, address: "Address 41" },
    { id: 42, name: "User 42", age: 2, address: "Address 42" },
    { id: 43, name: "User 43", age: 50, address: "Address 43" },
    { id: 44, name: "User 44", age: 5, address: "Address 44" },
    { id: 45, name: "User 45", age: 0, address: "Address 45" },
    { id: 46, name: "User 46", age: 84, address: "Address 46" },
    { id: 47, name: "User 47", age: 8, address: "Address 47" },
    { id: 48, name: "User 48", age: 23, address: "Address 48" },
    { id: 49, name: "User 49", age: 18, address: "Address 49" },
  ],
};

export const vehicles: Database<Vehicle> = {
  query: "SELECT * FROM vehicles",
  data: [
    { id: 0, name: "Vehicle 0", model: "Model 0", year: 2000 },
    { id: 1, name: "Vehicle 1", model: "Model 1", year: 2001 },
    { id: 2, name: "Vehicle 2", model: "Model 2", year: 2002 },
    { id: 3, name: "Vehicle 3", model: "Model 3", year: 2003 },
    { id: 4, name: "Vehicle 4", model: "Model 4", year: 2004 },
    { id: 5, name: "Vehicle 5", model: "Model 5", year: 2005 },
    { id: 6, name: "Vehicle 6", model: "Model 6", year: 2006 },
    { id: 7, name: "Vehicle 7", model: "Model 7", year: 2007 },
    { id: 8, name: "Vehicle 8", model: "Model 8", year: 2008 },
    { id: 9, name: "Vehicle 9", model: "Model 9", year: 2009 },
    { id: 10, name: "Vehicle 10", model: "Model 10", year: 2010 },
    { id: 11, name: "Vehicle 11", model: "Model 11", year: 2011 },
    { id: 12, name: "Vehicle 12", model: "Model 12", year: 2012 },
    { id: 13, name: "Vehicle 13", model: "Model 13", year: 2013 },
    { id: 14, name: "Vehicle 14", model: "Model 14", year: 2014 },
    { id: 15, name: "Vehicle 15", model: "Model 15", year: 2015 },
    { id: 16, name: "Vehicle 16", model: "Model 16", year: 2016 },
    { id: 17, name: "Vehicle 17", model: "Model 17", year: 2017 },
    { id: 18, name: "Vehicle 18", model: "Model 18", year: 2018 },
    { id: 19, name: "Vehicle 19", model: "Model 19", year: 2019 },
    { id: 20, name: "Vehicle 20", model: "Model 20", year: 2020 },
    { id: 21, name: "Vehicle 21", model: "Model 21", year: 2021 },
    { id: 22, name: "Vehicle 22", model: "Model 22", year: 2022 },
    { id: 23, name: "Vehicle 23", model: "Model 23", year: 2023 },
    { id: 24, name: "Vehicle 24", model: "Model 24", year: 2024 },
    { id: 25, name: "Vehicle 25", model: "Model 25", year: 2025 },
    { id: 26, name: "Vehicle 26", model: "Model 26", year: 2026 },
  ],
};

export const locations: Database<Location> = {
  query: "SELECT * FROM locations",
  data: [
    {
      id: 0,
      name: "Location 0",
      address: "Address 0",
      city: "City 0",
      state: "State 0",
    },
    {
      id: 1,
      name: "Location 1",
      address: "Address 1",
      city: "City 1",
      state: "State 1",
    },
    {
      id: 2,
      name: "Location 2",
      address: "Address 2",
      city: "City 2",
      state: "State 2",
    },
    {
      id: 3,
      name: "Location 3",
      address: "Address 3",
      city: "City 3",
      state: "State 3",
    },
    {
      id: 4,
      name: "Location 4",
      address: "Address 4",
      city: "City 4",
      state: "State 4",
    },
    {
      id: 5,
      name: "Location 5",
      address: "Address 5",
      city: "City 5",
      state: "State 5",
    },
    {
      id: 6,
      name: "Location 6",
      address: "Address 6",
      city: "City 6",
      state: "State 6",
    },
    {
      id: 7,
      name: "Location 7",
      address: "Address 7",
      city: "City 7",
      state: "State 7",
    },
    {
      id: 8,
      name: "Location 8",
      address: "Address 8",
      city: "City 8",
      state: "State 8",
    },
    {
      id: 9,
      name: "Location 9",
      address: "Address 9",
      city: "City 9",
      state: "State 9",
    },
    {
      id: 10,
      name: "Location 10",
      address: "Address 10",
      city: "City 10",
      state: "State 10",
    },
    {
      id: 11,
      name: "Location 11",
      address: "Address 11",
      city: "City 11",
      state: "State 11",
    },
    {
      id: 12,
      name: "Location 12",
      address: "Address 12",
      city: "City 12",
      state: "State 12",
    },
    {
      id: 13,
      name: "Location 13",
      address: "Address 13",
      city: "City 13",
      state: "State 13",
    },
    {
      id: 14,
      name: "Location 14",
      address: "Address 14",
      city: "City 14",
      state: "State 14",
    },
    {
      id: 15,
      name: "Location 15",
      address: "Address 15",
      city: "City 15",
      state: "State 15",
    },
    {
      id: 16,
      name: "Location 16",
      address: "Address 16",
      city: "City 16",
      state: "State 16",
    },
    {
      id: 17,
      name: "Location 17",
      address: "Address 17",
      city: "City 17",
      state: "State 17",
    },
    {
      id: 18,
      name: "Location 18",
      address: "Address 18",
      city: "City 18",
      state: "State 18",
    },
    {
      id: 19,
      name: "Location 19",
      address: "Address 19",
      city: "City 19",
      state: "State 19",
    },
    {
      id: 20,
      name: "Location 20",
      address: "Address 20",
      city: "City 20",
      state: "State 20",
    },
    {
      id: 21,
      name: "Location 21",
      address: "Address 21",
      city: "City 21",
      state: "State 21",
    },
    {
      id: 22,
      name: "Location 22",
      address: "Address 22",
      city: "City 22",
      state: "State 22",
    },
    {
      id: 23,
      name: "Location 23",
      address: "Address 23",
      city: "City 23",
      state: "State 23",
    },
    {
      id: 24,
      name: "Location 24",
      address: "Address 24",
      city: "City 24",
      state: "State 24",
    },
    {
      id: 25,
      name: "Location 25",
      address: "Address 25",
      city: "City 25",
      state: "State 25",
    },
    {
      id: 26,
      name: "Location 26",
      address: "Address 26",
      city: "City 26",
      state: "State 26",
    },
    {
      id: 27,
      name: "Location 27",
      address: "Address 27",
      city: "City 27",
      state: "State 27",
    },
    {
      id: 28,
      name: "Location 28",
      address: "Address 28",
      city: "City 28",
      state: "State 28",
    },
    {
      id: 29,
      name: "Location 29",
      address: "Address 29",
      city: "City 29",
      state: "State 29",
    },
    {
      id: 30,
      name: "Location 30",
      address: "Address 30",
      city: "City 30",
      state: "State 30",
    },
    {
      id: 31,
      name: "Location 31",
      address: "Address 31",
      city: "City 31",
      state: "State 31",
    },
    {
      id: 32,
      name: "Location 32",
      address: "Address 32",
      city: "City 32",
      state: "State 32",
    },
    {
      id: 33,
      name: "Location 33",
      address: "Address 33",
      city: "City 33",
      state: "State 33",
    },
    {
      id: 34,
      name: "Location 34",
      address: "Address 34",
      city: "City 34",
      state: "State 34",
    },
    {
      id: 35,
      name: "Location 35",
      address: "Address 35",
      city: "City 35",
      state: "State 35",
    },
    {
      id: 36,
      name: "Location 36",
      address: "Address 36",
      city: "City 36",
      state: "State 36",
    },
    {
      id: 37,
      name: "Location 37",
      address: "Address 37",
      city: "City 37",
      state: "State 37",
    },
    {
      id: 38,
      name: "Location 38",
      address: "Address 38",
      city: "City 38",
      state: "State 38",
    },
    {
      id: 39,
      name: "Location 39",
      address: "Address 39",
      city: "City 39",
      state: "State 39",
    },
    {
      id: 40,
      name: "Location 40",
      address: "Address 40",
      city: "City 40",
      state: "State 40",
    },
    {
      id: 41,
      name: "Location 41",
      address: "Address 41",
      city: "City 41",
      state: "State 41",
    },
    {
      id: 42,
      name: "Location 42",
      address: "Address 42",
      city: "City 42",
      state: "State 42",
    },
    {
      id: 43,
      name: "Location 43",
      address: "Address 43",
      city: "City 43",
      state: "State 43",
    },
  ],
};

export const database = [locations, users, vehicles];
